name       : haskell-glob
version    : 0.7.14
release    : 1
source     :
    - http://hackage.haskell.org/package/Glob-0.7.14/Glob-0.7.14.tar.gz : 2837b88916e8ba4314fdbb556de8b0e7f577b848d3e80a08959b6ef47e1c842b
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library for globbing - matching patterns against file paths. 
description: |
    A library for globbing - matching patterns against file paths. 
builddeps  :
    - haskell-cabal-install
    - haskell-dlist
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
