name       : haskell-glob
version    : 0.10.0
release    : 3
source     :
    - https://hackage.haskell.org/package/Glob-0.10.0/Glob-0.10.0.tar.gz : 473355bd6ba0a97902e0edada1acbc0d76cfda77596f0188b2cc0ae34272a324
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library for globbing - matching patterns against file paths.
description: |
    A library for globbing - matching patterns against file paths.
builddeps  :
    - haskell-cabal-install
    - haskell-dlist-devel
    - haskell-transformers-compat-devel
rundeps    :
    - devel:
        - haskell-dlist-devel
        - haskell-transformers-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
