name       : haskell-glob
version    : 0.9.2
release    : 2
source     :
    - https://hackage.haskell.org/package/Glob-0.9.2/Glob-0.9.2.tar.gz : 8fc7134e9a930dd53fd168f200bde8ca07905365788f70adc6a1a4c413667ce5
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library for globbing - matching patterns against file paths.
description: "A library for globbing - matching patterns against file paths. \n"
builddeps  :
    - haskell-cabal-install
    - haskell-dlist
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
